# docker build -t thumbor-alpine --build-arg BUILDKIT_INLINE_CACHE=1 -f ./docker/thumbor-7.3/Dockerfile-alpine . && docker run --rm -it thumbor-alpine
# Full-featured Thumbor docker image
FROM python:3.10-alpine

LABEL org.opencontainers.image.source=https://github.com/beeyev/thumbor-s3-docker

ENV TERM="xterm-256color" \
LANGUAGE="en_US.UTF-8" \
LANG="en_US.UTF-8" \
LC_TIME="en_GB.UTF-8"

ENV PYTHONUNBUFFERED=1 \
PYTHONDONTWRITEBYTECODE=1

# Enable jpegtran optimizer https://thumbor.readthedocs.io/en/latest/jpegtran.html#jpegtran
ENV OPTIMIZERS="['thumbor.optimizers.jpegtran']"

WORKDIR /app/

RUN set -eux \
    && apk add --quiet --no-cache \
        bash \
        tzdata \
        figlet \
        nano \
        curl \
        iputils \
        tini \
        # jpegtran (libjpeg-turbo-utils) is a Thumbor requirement for optimizing JPEG images
        libjpeg-turbo-utils

RUN set -eux \
    && apk add --quiet --no-cache --virtual .build-deps \
    # thumbor requirements:
    curl-dev g++ \
    # Thumbor
    && pip install --quiet --no-cache-dir --upgrade pip \
    && pip install --quiet --no-cache-dir \
        # Jinja2 and envtpl are required to work with environtment variables
        Jinja2==3.0.* envtpl==0.6.* \
        # pycurl is required for thumbor
        pycurl==7.* thumbor==7.3.* thumbor-aws==0.4.* tc_prometheus==2.* \
    && thumbor --version && envtpl --help \
    #
    ## Optional extensions
    #
    ## `gifsicle` is a Thumbor requirement for better processing of GIF images
    && apk add --quiet --no-cache gifsicle \
    #
    ## `ffmpeg` is used by Thumbor for rendering animated images as GIFV
    && apk add --quiet --no-cache ffmpeg \
    #
    ## cairosvg is for reading SVG files.
    && apk add --quiet --no-cache cairo \
    && apk add --quiet --no-cache --virtual .build-deps-cairosvg libffi-dev \
    && pip install --quiet --no-cache-dir cairosvg==2.5.* \
    && apk del .build-deps-cairosvg \
    #
    ## py3exiv2 is required for working with EXIF metadata
    && apk add --quiet --no-cache exiv2 boost-dev \
    && apk add --quiet --no-cache --virtual .build-deps-py3exiv2 exiv2-dev build-base \
    && pip install --quiet --no-cache-dir py3exiv2==0.11.* \
    && apk del .build-deps-py3exiv2 \
    #
    # Cleanup
    && apk del .build-deps

#set bash as a default shell
RUN set -eux \
    && echo "" > /root/.ash_history \
    && sed -i -e "s/bin\/ash/bin\/bash/" /etc/passwd

#These params meant to be set by CI
ARG BUILD_DATE
ENV BUILD_DATE=${BUILD_DATE}
ARG BUILD_INFO
ENV BUILD_INFO=${BUILD_INFO}

ENV LOG_LEVEL="warning"
ENV PORT="8888"
ENV NUM_PROCESSES=0

COPY ./docker/config/thumbor/thumbor.conf.tpl /usr/local/etc/thumbor.conf.tpl
COPY --chmod=0755 ./docker/config/etc/docker-entrypoint.sh /docker-entrypoint.sh

RUN set -eux \
    # /data/ dir is used by thumbor
    && mkdir /data/ \
    && mkdir /docker-entrypoint.init.d/ \
    # Running `thumbor-doctor` to smoke test functionality
    && thumbor-doctor

# Enable nobody user
#RUN set -eux \
#    && chown -R nobody:nogroup /usr/local/etc/ /data/ /docker-entrypoint.init.d/
#USER nobody

ENTRYPOINT ["tini", "--", "/docker-entrypoint.sh"]
CMD ["thumbor"]

EXPOSE ${PORT}
HEALTHCHECK --timeout=15s CMD curl --silent --fail http://127.0.0.1:${PORT}/healthcheck
