# docker build -t thumbor-slim-alpine --build-arg BUILDKIT_INLINE_CACHE=1 -f ./docker/thumbor-7.2/Dockerfile-slim-alpine . && docker run --rm -it thumbor-slim-alpine
# Slim Thumbor docker image
FROM python:3.11.0-alpine

LABEL org.opencontainers.image.source=https://github.com/beeyev/thumbor-s3-docker

ENV TERM="xterm-256color" \
LANGUAGE="en_US.UTF-8" \
LANG="en_US.UTF-8" \
LC_TIME="en_GB.UTF-8"
# Enable jpegtran optimizer https://thumbor.readthedocs.io/en/latest/jpegtran.html#jpegtran
ENV OPTIMIZERS="['thumbor.optimizers.jpegtran']"

WORKDIR /app

RUN set -eux \
  && apk add --quiet --no-cache \
    bash \
    tzdata \
    figlet \
    nano \
    curl \
    iputils \
    tini \
    # jpegtran (libjpeg-turbo-utils) is a Thumbor requirement for optimizing JPEG images
    libjpeg-turbo-utils

RUN set -eux \
  && apk add --quiet --no-cache --virtual .build-deps \
    # thumbor requirements:
    curl-dev g++

RUN set -eux \
    && pip install --quiet --no-cache-dir --upgrade pip \
    && pip install --quiet --no-cache-dir \
        # Jinja2 and envtpl are required to work with environtment variables
        Jinja2==3.0.* envtpl==0.6.* \
        # pycurl is required for thumbor
        pycurl==7.45.* thumbor==7.2.* thumbor-aws==0.4.* tc_prometheus==2.* \
    && thumbor --version && envtpl --help

##
## Optional extensions
##
## `gifsicle` is a Thumbor requirement for better processing of GIF images
RUN apk add --quiet --no-cache gifsicle

# Cleanup
RUN set -eux \
    && apk del .build-deps \
    && rm -rf /var/cache/apk/* \
    && rm -rf /root/.cache

#set bash as a default shell
RUN set -eux \
    && echo "" > /root/.ash_history \
    && sed -i -e "s/bin\/ash/bin\/bash/" /etc/passwd

#These params meant to be set by CI
ARG BUILD_DATE
ENV BUILD_DATE=${BUILD_DATE}
ARG BUILD_INFO
ENV BUILD_INFO=${BUILD_INFO}

ENV LOG_LEVEL="warning"
ENV PORT="8888"
ENV NUM_PROCESSES=0

COPY ./docker/config/thumbor/thumbor.conf.tpl /usr/local/etc/thumbor.conf.tpl
COPY --chmod=0755 ./docker/config/etc/docker-entrypoint.sh /docker-entrypoint.sh

RUN set -eux \
    # /data/ dir is used by thumbor
    && mkdir /data/ \
    && mkdir /docker-entrypoint.init.d/

# Enable nobody user
#RUN set -eux \
#    && chown -R nobody:nogroup /usr/local/etc/ /data/ /docker-entrypoint.init.d/
#USER nobody

ENTRYPOINT ["tini", "--", "/docker-entrypoint.sh"]
CMD ["thumbor"]

EXPOSE ${PORT}
HEALTHCHECK --timeout=15s CMD curl --silent --fail http://127.0.0.1:${PORT}/healthcheck
