on:
  workflow_call:
    inputs:
      DOCKER_REGISTRY_IMAGE:
        required: true
        type: string
      DOCKERFILE_PATH:
        required: true
        type: string

jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout branch - ${{ github.head_ref || github.ref_name }}
        uses: actions/checkout@v3

#      - name: Debugging with tmate
#        uses: mxschmitt/action-tmate@v3.16

      - name: Prepare Build Env Variables
        uses: ./.github/actions/prepare-env-variables/
        id: prepare-build-env-variables

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to registry - ${{ inputs.DOCKER_REGISTRY_IMAGE }}
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          context: .
          file: ${{ inputs.DOCKERFILE_PATH }}
          cache-from: type=registry,ref=${{ inputs.DOCKER_REGISTRY_IMAGE }}
          cache-to: type=inline
          build-args: |
            BUILD_DATE=${{ steps.prepare-build-env-variables.outputs.BUILD_DATE }}
            BUILD_FINGERPRINT=${{ steps.prepare-build-env-variables.outputs.BUILD_FINGERPRINT }}
          tags: ${{ inputs.DOCKER_REGISTRY_IMAGE }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          push: true
