# Alexander Tebiev - https://github.com/beeyev
name: Build Production Docker Images

on:
  push:
    branches: [ master ]

  schedule:
    - cron: "23 1 2 * *"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  docker-image-deploy:
    uses: ./.github/workflows/callable-build-docker-image.yml
    strategy:
      fail-fast: false
      matrix:
        baseDist: [ 'slim-alpine', 'debian' ]
        versionMinor: [ '7.7' ]
        versionMajor: [ '7' ]
    name: Build Production Docker Images / ${{ matrix.versionMinor }}-${{ matrix.baseDist }}
    with:
      DOCKER_REGISTRY_IMAGE: |
        ghcr.io/beeyev/thumbor-s3:${{ matrix.baseDist }}
        ghcr.io/beeyev/thumbor-s3:${{ matrix.versionMinor }}-${{ matrix.baseDist }}
        ghcr.io/beeyev/thumbor-s3:${{ matrix.versionMajor }}-${{ matrix.baseDist }}
        beeyev/thumbor-s3:${{ matrix.baseDist }}
        beeyev/thumbor-s3:${{ matrix.versionMinor }}-${{ matrix.baseDist }}
        beeyev/thumbor-s3:${{ matrix.versionMajor }}-${{ matrix.baseDist }}
        quay.io/beeyev/thumbor-s3:${{ matrix.baseDist }}
        quay.io/beeyev/thumbor-s3:${{ matrix.versionMinor }}-${{ matrix.baseDist }}
        quay.io/beeyev/thumbor-s3:${{ matrix.versionMajor }}-${{ matrix.baseDist }}
      DOCKERFILE_PATH: ./docker/thumbor-${{ matrix.versionMinor }}/${{ matrix.baseDist }}.Dockerfile
      PLATFORMS: linux/amd64,linux/arm64
    secrets: inherit

  update-docker-hub-repo-description:
    name: Update Docker repo description
    runs-on: ubuntu-latest
    needs: docker-image-deploy
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Update Docker Hub repo description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: beeyev/thumbor-s3
          #short-description: ${{ github.event.repository.description }}

      - name: Update Quay.io description
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_APIKEY: ${{ secrets.QUAY_TOKEN }}
        with:
          destination_container_repo: quay.io/beeyev/thumbor-s3
          provider: quay
          readme_file: 'README.md'
