# Alexander Tebiev - https://github.com/beeyev
name: Build Production Docker Images

on:
  push:
    branches: [ master ]

  schedule:
    - cron: "23 1 2 * *"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  docker-image-deploy:
    uses: ./.github/workflows/callable-build-docker-image.yml
    strategy:
      fail-fast: false
      matrix:
        baseDist: [ 'slim-alpine', 'alpine' ]
        versionMinor: [ '7.5' ]
        versionMajor: [ '7' ]
    name: Build Production Docker Images / ${{ matrix.versionMinor }}-${{ matrix.baseDist }}
    with:
      DOCKER_REGISTRY_IMAGE: |
        ghcr.io/beeyev/thumbor-s3:${{ matrix.baseDist }}
        ghcr.io/beeyev/thumbor-s3:${{ matrix.versionMinor }}-${{ matrix.baseDist }}
        ghcr.io/beeyev/thumbor-s3:${{ matrix.versionMajor }}-${{ matrix.baseDist }}
        beeyev/thumbor-s3:${{ matrix.baseDist }}
        beeyev/thumbor-s3:${{ matrix.versionMinor }}-${{ matrix.baseDist }}
        beeyev/thumbor-s3:${{ matrix.versionMajor }}-${{ matrix.baseDist }}
      DOCKERFILE_PATH: ./docker/thumbor-${{ matrix.versionMinor }}/Dockerfile-${{ matrix.baseDist }}
    secrets: inherit

  update-docker-hub-repo-description:
    name: Update Docker Hub repo description
    runs-on: ubuntu-latest
    needs: docker-image-deploy
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Update Docker Hub repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: beeyev/thumbor-s3
          #short-description: ${{ github.event.repository.description }}
