name: Build Production Docker Images

on:
  push:
    branches: [ master ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  docker-image-deploy:
    name: Build Production Docker Images
    uses: ./.github/workflows/callable-build-docker-image.yml
    strategy:
      fail-fast: false
      matrix:
        baseDist: [ 'slim-alpine', 'alpine' ]
        versionMinor: [ '7.5' ]
        versionMajor: [ '7' ]
    with:
      DOCKER_REGISTRY_IMAGE: |
        ghcr.io/${{ github.repository_owner }}/thumbor-s3:${{ matrix.baseDist }}-${{ matrix.versionMinor }}-test
        ghcr.io/${{ github.repository_owner }}/thumbor-s3:${{ matrix.baseDist }}-${{ matrix.versionMajor }}-test
      DOCKERFILE_PATH: ./docker/thumbor-7.5/Dockerfile-${{ matrix.baseDist }}

#  docker-image-deploy:
#    name: Build docker test image
#    uses: ./.github/workflows/callable-build-docker-image.yml
#    strategy:
#      fail-fast: false
#      matrix:
#        baseDist: [ 'slim-alpine', 'alpine' ]
#    with:
#      DOCKER_REGISTRY_IMAGE: ghcr.io/thumbor-s3:${{ matrix.baseDist }}-test
#      DOCKERFILE_PATH: ./docker/thumbor-7.5/Dockerfile-${{ matrix.baseDist }}
