name: Build Test Docker Images

on:
  pull_request:
    types: [labeled]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  initialization:
    name: Initialization
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    if: contains(github.event.label.name, 'make-test-build')
#    if: |
#      (github.event.action == 'labeled' && github.event.label.name == 'make-test-build') ||
#      (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'make-test-build'))
    steps:
      - uses: crazy-max/ghaction-dump-context@v2
      - name: Remove `test-build` label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: make-test-build
          fail_on_error: true

      - name: Sticky Pull Request Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            > [Building test docker images...](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

  docker-image-deploy:
    name: Build docker production images
    uses: ./.github/workflows/callable-build-docker-image.yml
    strategy:
      fail-fast: false
      matrix:
        baseDist: [ 'slim-alpine', 'alpine' ]
        versionMinor: [ '7.5' ]
        versionMajor: [ '7' ]
    with:
      DOCKER_REGISTRY_IMAGE: |
        ghcr.io/${{ github.repository_owner }}/thumbor-s3:${{ matrix.versionMinor }}-${{ matrix.baseDist }}-test
        ghcr.io/${{ github.repository_owner }}/thumbor-s3:${{ matrix.versionMajor }}-${{ matrix.baseDist }}-test
      DOCKERFILE_PATH: ./docker/thumbor-7.5/Dockerfile-${{ matrix.baseDist }}

#  docker-image-deploy:
#    name: Build docker test image
#    uses: ./.github/workflows/callable-build-docker-image.yml
#    strategy:
#      fail-fast: false
#      matrix:
#        baseDist: [ 'slim-alpine', 'alpine' ]
#    with:
#      DOCKER_REGISTRY_IMAGE: ghcr.io/${{ github.repository_owner }}/thumbor-s3:${{ matrix.baseDist }}-test
#      DOCKERFILE_PATH: ./docker/thumbor-7.5/Dockerfile-${{ matrix.baseDist }}
